name: Dart Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Install coverage
        run: pub global activate coverage

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed lib test

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Run Tests
        run: pub run test --coverage="coverage"

      - name: Format coverage
        run: pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
